# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: ':title/index.html'

# Markdown library
markdown: kramdown

# Site settings
baseurl: "/"
url: "http://joshuajohnson.co.uk"
github: "https://github.com/jshjohnson"
twitter: "https://twitter.com/jshjohnson"
twitterAnchor: "@jshjohnson"

# Varibles
sitename: "Josh Johnson - Front-end Developer"
disqus: "joshjohnsonportfolio"

